mattermost/mattermost-plugin-msteams

- webapp/package.json
Added Github Actions workflows
> Added Github Actions workflows

- README.md
- docs/azure_setup.md
- docs/plugin_setup.md
> Added documentation

- server/message_hooks_test.go
- server/testutils/data.go
- server/testutils/mock.go
Added unit test cases for some functions of message_hooks.go file:
- `MessageWillBePosted`
- `ReactionHasBeenAdded`
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/16
> Added unit test cases for message_hooks.go file

- server/command.go
- server/command_test.go
> Avoid a MS Teams channel to be connected from multiple Mattermost channels

- server/handlers/handlers.go
> Fixed the deletion of reply posts

- server/command.go
- server/handlers/attachments.go
- server/handlers/converters.go
- server/handlers/getters.go
- server/handlers/handlers.go
- server/store/store.go
- server/store/storemodels/storemodels.go
> Remove the requirement of a connected bot account to allow to receive messages.

- server/store/store.go
Fixed the issue of plugin not working with MySQL
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/11
> [MI-2966] Fixed the issue of plugin not working with MySQL by fixing the syntax of a query

- server/command.go
- server/command_test.go
- Fixed issues of wrong error messages on unlinking a channel and disconnecting user
- Fixed existing and added new unit tests
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/69
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/70
> [MI-2987] Fixed issues of wrong error messages on unlinking a channel and disconnecting user

- server/message_hooks.go
> Not propagate system messages posts

- README.md
- docs/azure_setup.md
- docs/plugin_setup.md
- plugin.json
- server/command.go
- server/command_test.go
- Updated the documentation
- Modified some messages
- Fixed some typos
- 
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/84
> [MI-3005] Updated documentation, fixed some typos and modified some messages

- server/handlers/handlers.go
- server/handlers/handlers_test.go
Add unit test cases for `handlers.go` file
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/36
> Add unit test cases for handlers.go file

- server/api.go
- server/message_hooks.go
- server/plugin.go
Changed the way of using plugin's configuration settings everywhere
#89
> [MI-3030] Changed the way of using plugin's configuration settings to fix issue #89

- webapp/src/index.tsx
- webapp/src/selectors/index.tsx
This PR sets the site URL for frontend operations
Fixes https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/104
> Use Site URL for frontend operations

- server/command_test.go
Added server unit for command.go file
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/18
> [MI-3065] Add unit test cases for command.go file

- docs/azure_setup.md
Added `ChannelMessage.Read.All` in the delegated permission list in the documentation
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/119
> [MI-3088] Added a new delegated permission in the documentation

- server/api.go
- server/msteams/client.go
Fixed the issue of Excel files not being sent from Mattemost to MS Teams
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/121
> [MI-3092] Fixed the issue of Excel files not being sent from MM to MS Teams

- server/msteams/client.go
Added the logic of parsing the errors received from the Graph SDK and making them verbose
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/127
> [MI-3096] Added the logic of parsing the errors received from the Graph SDK

- server/msteams/client.go
Added generic code for handling different types of extensions
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/121
> [MI-3098] Added generic code for handling different types of extensions

- docs/azure_setup.md
Added latest updates in the documentation
> [MI-3099] Modified the documentation according to some latest changes

- server/handlers/handlers.go
- server/handlers/handlers_test.go
> Fix clean up of the last reaction of the post from MS-Teams

- server/api.go
- server/msteams/client.go
Fix the issue of the user not being able to connect due to an email case sensitivity issue
> [MI-3113] Fix email case sensitivity issue

- server/plugin.go
Add logs for showing the count of MS Teams and MM users
> [MI-3123] Add logs for count of MS Teams and MM users

- server/handlers/converters.go
- server/handlers/converters_test.go
- server/handlers/handlers.go
Fixed issue 138 of emoji not being supported from Teams to MM
#138
> [MI-3119] Fix issue 138 of emoji not supported from Teams to MM

- server/message_hooks.go
- server/msteams/client.go
Added a TODO comment in the update function for the channels to handle attachments
Added the logic for getting the existing attachments from a post and sending them in the update API
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/172
> [MI-3172] Fixed the issue of attachments being removed when post is edited in MM

- server/store/crypt.go
- server/store/crypt_test.go
- Changed the encryption algorithm
- Modified the unit tests according to the new code
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/177
> [MI-3190] Changed the encryption algorithm

- server/plugin.go
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/180
> [MI-3211] Fixed the biasing in the logic of generating random password

- server/msteams/client.go
> Explored about getting different URLs for some file types from Teams and added a comment for the same (#11)

- server/handlers/attachments.go
- server/handlers/attachments_test.go
Modified the unit tests a little bit
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/178
> [MI-3198] Added the logic to check attachment size and attachment count when receiving attachments from MS Teams

- server/message_hooks.go
- server/message_hooks_test.go
- server/testutils/data.go
Fix the issue of attachments not working correctly due to issue in naming of attachments
> [MI-3208] Fix issue in naming of attachments

- server/message_hooks.go
- server/message_hooks_test.go
Fixed issue 171 of punctuation marks not working properly from MM to Teams
#171
> [MI-3201] Fix issue 171 of punctuation marks not working from MM to Teams

- plugin.json
Bump plugin version to v0.3.11
> [MI-3358] Bump plugin version to v0.3.11

- plugin.json
- server/handlers/handlers.go
Fix issue of messages being posted from inactive users on Mattermost corresponding to MS Teams user
> [MI-3368] Fix issue of messages being posted from inactive users on Mattermost corresponding to MS Teams user

- plugin.json
Bump plugin version to v0.3.12
> Bump plugin version to v0.3.12

- server/api.go
- server/api_test.go
- server/command.go
- server/command_test.go
- server/handlers/attachments.go
- server/handlers/attachments_test.go
- server/handlers/converters.go
- server/handlers/converters_test.go
- server/handlers/getters.go
- server/handlers/getters_test.go
- server/handlers/handlers.go
- server/handlers/handlers_test.go
- server/message_hooks.go
- server/message_hooks_test.go
- server/msteams/client.go
- server/plugin.go
- server/plugin_test.go
- Fixed the logging messages everywhere
- Modified the unit tests
> [MI-3396] Fixed the logging messages everywhere in the plugin along with the unit tests

- server/handlers/attachments.go
- server/handlers/attachments_test.go
- server/handlers/converters.go
- server/handlers/converters_test.go
- server/handlers/handlers.go
- server/handlers/handlers_test.go
Fix issue of attachments in DMs/GMs from Teams to MM
> [MI-3407] Fix issue of attachments in DMs/GMs from Teams to MM

- server/message_hooks.go
- server/message_hooks_test.go
- server/msteams/client.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
Fix the issue of attachments sent from MM to Teams not opening for a receiver due to permissions issue
#248
> [MI-3420] Fix issue of attachments sent from MM to Teams not opening for receiver due to permissions issue

- plugin.json
> Bump plugin version

- server/message_hooks.go
- Fixed the issue of reactions behaviour when user not connected and bot account is connected
> [MI-3410] Fixed the issue of reactions behaviour when user not connected and bot account is connected

- server/message_hooks.go
- server/message_hooks_test.go
- server/msteams/client.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
Add pagination in API to get chats and refactor code to resolve TODO comments
> [MI-3427] Add pagination in API to get chats and refactor code

- plugin.json
> Bump plugin version to 1.0.6

- plugin.json
> Bump plugin version to 1.0.7

- server/command.go
- server/monitor/monitor.go
- server/monitor/subscriptions.go
- server/monitor/subscriptions_test.go
- server/msteams/client.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
- server/plugin.go
- server/plugin_test.go
- server/store/mocks/Store.go
- server/store/store.go
- server/store/store_test.go
- server/store/storemodels/storemodels.go
- Optimise subscriptions monitor system.
- Remove refreshing of subscriptions during processing of activity.
> [MI-3442] Optimise subscriptions monitor system

- server/monitor/subscriptions.go
- server/monitor/subscriptions_test.go
- server/msteams/client.go
- server/plugin.go
Update monitor system for channel subscriptions
#283
> [MI-3478] Update monitor system for channel subscriptions

- server/handlers/attachments.go
- server/handlers/attachments_test.go
- server/msteams/client.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
Fixed the issue of checking file size before downloading it from Teams
> [MI-3487] Fixed the issue of checking file size before downloading it from Teams

- server/api.go
- server/handlers/handlers.go
- server/handlers/handlers_test.go
- server/message_hooks.go
- server/msteams/client.go
Fix content-type of APIs and remove additional information from logs
> [MI-3485] Fix content-type of APIs and remove additional information from logs

- server/handlers/converters.go
- server/handlers/converters_test.go
- server/handlers/handlers.go
- server/handlers/handlers_test.go
- server/testutils/data.go
- Modified the msgToPost function to add <p> tag if missing from message
- Fixed the failing unit test of converters file
- Modified the order of checking duplicate post in the handleCreatedActivity function
Fixes #309
> [MI-3521] Fixed the issue of emojis showing as html from Teams to MM

- docs/plugin_setup.md
> [MI-3553] Update documentation

- server/handlers/handlers.go
Update queue and workers size in handlers
> [MI-3555] Update queue and workers size in handlers

- server/command_test.go
- server/handlers/handlers.go
- server/message_hooks.go
- server/message_hooks_test.go
- server/msteams/client.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
- server/testutils/data.go
Add batching in APIs in various client functions
#331
> [MI-3559] Add batching in APIs in various client functions

- docs/ISSUE_TEMPLATE/bug_report.md
- docs/ISSUE_TEMPLATE/enhancement.md
- server/command_test.go
> [MI-3573] Add issue template

- plugin.json
> Bump plugin version to 1.1.1

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enhancement.md
> [MI-3573] Fix issue template structure

- README.md
Update promote slash command documentation
> [MI-3621] Update promote slash command documentation

- server/handlers/handlers.go
- server/plugin.go
- Fix panic on running of sync user job
- Fix issue 350 of panic causing on adding of the reaction on a post
#350
> [MI-3645] Fix issue of panics on running of sync users and adding a reaction

- server/handlers/handlers.go
- server/plugin.go
- server/store/store_test.go
- Fix issue of panic from sync user functionality
- Fix issue 350 of panic causing due to addition of reaction
#350
> [MI-3645] Fix issue of panic from sync user functionality and due to adding reaction

- plugin.json
> Bump plugin version to 1.2.1

- server/command.go
- server/command_test.go
- server/handlers/handlers.go
- server/handlers/handlers_test.go
- server/message_hooks.go
- server/message_hooks_test.go
- server/monitor/subscriptions.go
- server/monitor/subscriptions_test.go
- server/plugin_test.go
- server/store/mocks/Store.go
- server/store/store.go
- server/store/store_test.go
- Removed the use of transactions from where it was not needed
- Changed the definition of some store functions by changing the order of parameters
#344
> [MI-3634] Refactored some of the code according to review comments by Jesus

- README.md
- docs/plugin_setup.md
- server/command.go
- server/command_test.go
- Update show command
- Update documentation
> [MI-3652] Update show command and documentation

- server/api.go
- server/api_test.go
- server/command.go
- server/command_test.go
- server/get_teams_data.go
- server/handlers/handlers.go
- server/handlers/handlers_test.go
- server/message_hooks.go
- server/message_hooks_test.go
- server/monitor/subscriptions.go
- server/monitor/subscriptions_test.go
- server/msteams/client.go
- server/msteams/client_timerlayer/timerlayer.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
- server/plugin_test.go
- server/store/sqlstore/store.go
- server/store/sqlstore/store_test.go
- server/store/storemodels/storemodels.go
- server/testutils/data.go
APIs added:
1. Get msteams team list.
2. Get msteams team channels.
3. Get linked channels.
4. Link two channel.
5. Unlink two channels.
6. Disconnect user.
> Created APIs to be used in UI

- server/plugin.go
Fix issue in disabling of sync user job
> [MI-3749] Fix issue in disabling of sync user job

- .github/dependabot.yml
Not much here. We are enabling dependabot[golang|ghactions] for this repository. 
@lieut-data  Uncertain about the preferred package ecosystem and schedule intervals for this project. Please feel free to commit any necessary changes to this pull request.
Ticket: https://mattermost.atlassian.net/browse/CLD-6687
> [chore] Enable dependabot

- server/metrics/metrics.go
> Fixed an issue of panic occuring after receiving lifecycle change notifications

- docs/plugin_setup.md
Update documentation regarding certificate-based subscriptions and the auto-promotion of synthetic users.
> [MI-3773] Update documentation

- server/markdown/markdown.go
- server/markdown/markdown_test.go
Fixed the issue of headings not working properly from MS Teams to MM
Fixes #393
> [MI-3768] Fixed the issue of headings not working properly from MS Teams to MM

- LICENSE
- README.md
Adopt the source available license for this plugin.
Fixes: https://mattermost.atlassian.net/browse/MM-55748
> adopt source available license

- server/plugin.go
In debugging with a customer, we realized these logs would benefit from the Mattermost `user_id`.
None.
> add user_id to various logs in sync_user job

- docs/plugin_setup.md
Reformat config doc for readability
None
> Reformat configuration docs

- server/api.go
- webapp/src/index.tsx
Remove comments about the commented out features:
- Landing page after connect to select primary platform
- User setting to select primary platform
Fix: https://mattermost.atlassian.net/browse/MM-56856
> Remove comments for commented out features

- server/store/sqlstore/helper_test.go
I ran into a recent build error, but the details were buried. Surface them more explicitly if this happens again.
None,.
> avoid burying errors during test setup

- webapp/src/index.tsx
Fix links hard-coded to google.com to use the permalinks from the info-page instead.
Fixes: https://mattermost.atlassian.net/browse/MM-56959
> update google.com links

- server/plugin.go
- server/store/mocks/Store.go
- server/store/sqlstore/store.go
- server/store/store.go
- server/store/timerlayer/timerlayer.go
This uses the plugin-api to close the db connection the plugin is done with it. It should fix the connection leak for master db and for replica db.
> Fix replica conn leak

- assets/info-page/index.html
Updates text for Choose Primary Platform.
https://www.figma.com/file/BDolYCzc6CMCgVMa3U1p9B/MS-Teams-Sync---Choose-Primary-Platform?type=design&node-id=805-19549&mode=design&t=09nWqGQxgaGMpdRa-11
> Update text for Primary Platform selection

- server/monitor/monitor.go
- server/monitor/subscriptions.go
- server/testutils/mock.go
Add some extra info logs around subscriptions, giving visibility into changes that are occurring. Add some godoc while we're in here.
None
> more verbose logging around subscriptions

- server/monitor/monitor.go
Delay the monitoring job by at least 1 minute after startup to avoid a race where the plugin hasn't fully yet deployed in a mostly disabled environment.
```
{
"timestamp": "2024-03-30 15:06:00.011 -03:00",
"level": "info",
"msg": "Delaying the Monitoring System Job until at least 1 minute after startup",
"caller": "app/plugin_api.go:1004",
"plugin_id": "com.mattermost.msteams-sync"
}
{
"timestamp": "2024-03-30 15:07:00.016 -03:00",
"level": "info",
"msg": "Running the Monitoring System Job",
"caller": "app/plugin_api.go:1004",
"plugin_id": "com.mattermost.msteams-sync"
}
```
Fixes: https://mattermost.atlassian.net/browse/MM-57120
> MM-57120: delay monitoring job on startup

- server/message_hooks.go
- server/message_hooks_test.go
- server/msteams/client.go
- server/msteams/client_disconnectionlayer/disconnectionlayer.go
- server/msteams/client_timerlayer/timerlayer.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
Extract the portion of https://github.com/mattermost/mattermost-plugin-msteams/pull/560 that adds support for deleting messages from Mattermost and soft deleting those in Teams.
Fixes: https://mattermost.atlassian.net/browse/MM-56809
> MM-56809: support deleting messages from Mattermost

- server/command.go
- server/command_test.go
Log the error message if updating the user fails when running the promote command
https://mattermost.atlassian.net/browse/MM-56907
> [MM-56907] Log warn if updating the user fails when running the promote command

- server/command.go
- server/command_test.go
- server/handlers/getters.go
- server/handlers/getters_test.go
- server/message_hooks.go
- server/message_hooks_test.go
- server/plugin.go
- server/plugin_test.go
- server/store/sqlstore/migrations.go
- server/store/sqlstore/store.go
Cherry pick of #594 for v1.11.1
N/A
> Cherry pick of #594 for v1.11.1

- server/automute_channel.go
- server/automute_preferences.go
- server/ce2e/msteams_events_test.go
Trivial PR that fixes some linter warnings for a clean "Problems" view.
NONE
> Fix linter warnings for unused params

- server/api.go
(cherry picked from commit ee8c6096567ec400d6aca61d5a6ee8e4be97d0ca)
> CP-604 set user to bot, time to now (#604)

- server/command.go
- server/command_test.go
* reset to MM primary platform on disconnect
* revert file changes
* Fix linter
---------
Co-authored-by: Miguel de la Cruz <miguel@mcrx.me>
(cherry picked from commit a96acd178bdf650b2325da0bd966f7ce912b6bbf)
> CP-603 MM-57906 Update platform preference when disconnecting (#603)

- server/bot_messages.go
- server/handlers/handlers.go
(cherry picked from commit 4526af42b066ef1086f3bcbf1030e8dd247c0e33)
> Hide connect message, hide attachment message on update (#621)

- server/command.go
- server/command_test.go
This is a clone of https://github.com/mattermost/mattermost-plugin-msteams/pull/566 to be merged into `main` after https://github.com/mattermost/mattermost-plugin-msteams/pull/563.
Fixes: https://mattermost.atlassian.net/browse/MM-57508
> MM-57508: status slash command

- server/automute_preferences_test.go
Fixes unit test by adding new namespace
> Fixes unit test by adding new namespace

- server/notifications.go
honour user pref + update their last messaged received at
https://mattermost.atlassian.net/browse/MM-58300
https://mattermost.atlassian.net/browse/MM-58346
> [MM-58300 + MM-58346] honour user pref + update their last messaged received at

- server/command.go
- server/command_test.go
Turn off notification preference on disconnect
https://mattermost.atlassian.net/browse/MM-58374
> [MM-58374] Turn off notification preference on disconnect

- assets/account-connected/index.html
- server/api.go
- server/api_test.go
- server/bot_messages.go
- server/bot_messages_test.go
- server/command.go
- server/command_test.go
- server/msteams/client.go
- server/msteams/clientmodels/clientmodels.go
- server/notifications.go
- webapp/src/user_settings.ts
This implements a number of pieces of design review feedback, most notably:
* Eliminate the footer on notification messages and just link inline for reduced clutter
* Support group chat names (called "topics")
* Consistent terminology usage
Fixes: https://mattermost.atlassian.net/browse/MM-58436
> MM-58436: Notifications review feedback

- Makefile
Makefile - Allow releasing also from release.* branches
https://mattermost.atlassian.net/browse/CLD-7786
> Cld 7786 makefile semver bump allow release

- server/credentials.go
- server/credentials_test.go
- server/msteams/client.go
- server/msteams/client_disconnectionlayer/disconnectionlayer.go
- server/msteams/client_timerlayer/timerlayer.go
- server/msteams/clientmodels/clientmodels.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
To aid in debugging deployments, let's periodically check the application permissions and log those missing or redundant.
Fixes: https://mattermost.atlassian.net/browse/MM-59549
> Monitor permissions

- plugin.json
Update plugin description to match documentation.
None
> update plugin desc to match docs

- server/handlers.go
- server/metrics/mocks/Metrics.go
- server/store/mocks/Store.go
- server/store/sqlstore/public_methods.go
- server/store/sqlstore/store.go
- server/store/store.go
- server/store/timerlayer/timerlayer.go
Remove unused code in relation to `LastActivityAt`.
Fixes: https://mattermost.atlassian.net/browse/MM-60177
> remove unused LastActivityAt handling

- server/api.go
- server/bot_messages.go
- server/command.go
- server/connect.go
- server/connect_test.go
- server/handlers_test.go
- server/metrics/metrics.go
- server/msteams/client.go
- server/msteams/client_disconnectionlayer/disconnectionlayer.go
- server/msteams/client_timerlayer/timerlayer.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
- server/notifications.go
- server/presence.go
Improved logging:
* consistently log on connect/disconnect
* log whenever we send a bot message to a user, now including invite flow
* log on notification delivery
* fix various issues logging around chat notifications, including empty messages
Fixes: https://mattermost.atlassian.net/browse/MM-60060
Fixes: https://mattermost.atlassian.net/browse/MM-60061
> Improved logging

- server/api.go
Use constant comparison of webhook secret everywhere
https://mattermost.atlassian.net/browse/MM-63148
> [MM-63148] Constant comparison of webhook secret

- server/api_test.go
- server/iframe.go
This reverts commit 9763db2480d2f06f6c7787844baa1ddfc670fade.
None
> Revert "rm unneeded style-src directive"

- server/iframe.go
Fix linting issues from CSP cleanup.
None
> Fix linting

- .gitignore
Add Aider files to .gitignore.
NONE
> Update .gitignore for Aider

- server/mentions.go
> fix: remove unneeded log

- server/iframe.html
`noroute` -> `noRoute`
I would have thought this is something copilot would catch.
> fix(typo): noroute -> noRoute

- server/store/pluginstore/store.go
Hardcode the known Hub Teams app id in a bid to get the notifications demo working on Hub. We'll sort out the global `app_id` stomping later.
None.
> try hard-coding the hub app id to get notifications working

- server/msteams/client.go
> chore: add log line after user activity call

- server/msteams/client.go
Recover https://github.com/mattermost/mattermost-plugin-msteams/pull/828 after reset.
None
> fix: handle nil pointer in GetFileSizeAndDownloadURL (#828)
