- server/plugin_test.go
Added unit test cases for some functions of plugin.go file:
- `GetURL`
- `GetClientForUser`
- `GetClientForTeamsUser`
- `SyncUsers`
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/43
> Add unit test cases for plugin.go file

- server/store/store_test.go
Added unit test cases for some functions of store.go file:
- `GetAvatarCache`
- `SetAvatarCache`
- `CheckEnabledTeamByTeamID`
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/57
> Add unit test cases for store.go file

- server/command.go
- server/command_test.go
- Fixed the issue of wrong error message when trying to link/unlink DM or GM
- Fixed and added new unit tests
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/63
> [MI-2969] Fixed the issue of wrong error message when trying to link/unlink DM or GM

- server/msteams/client.go
- server/msteams/client_test.go
Added unit test cases for some functions of client.go file:
- `convertToMessage`
- `GetResourceIds`
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/55
> Add unit test cases for client.go file

- server/handlers/handlers.go
- server/message_hooks.go
- server/message_hooks_test.go
- server/msteams/client.go
- Added the logic in client functions to also send the user id along with the emoji name
- Modified the function definitions in the message hooks file
- Added another entry in the emoji map
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/32
> [MI-2961] Fixed the issue of reactions not being in sync

- server/message_hooks.go
Fixed the issue of message edits not being synced
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/53
> [MI-2992] Fixed the issue of message edits not being synced (issue #53)

- server/api.go
- server/handlers/converters.go
- server/handlers/converters_test.go
- server/handlers/handlers_test.go
- Added the logic of making an API call to the avatar API and checking if we get a valid profile picture or not
- Added error handling in the avatar API
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/52
> [MI-2991] Fixed the issue of incorrect bot profile picture while impersonating a user

- server/command.go
- server/command_test.go
- server/store/mocks/Store.go
- server/store/store.go
- server/store/store_test.go
Created a new function in the store for deleting the DM and GM channel prompt time
Added the logic for deleting the prompt time for a user when he disconnects
Fixed the failing unit tests and added some new unit tests
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/118
> [MI-3085] Added the logic for re-prompting the user in DMs an GMs if he has connected and disconnected again

- server/msteams/client.go
Fixed the issue of some attachment extensions not working
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/121
> [MI-3098] Fixed the issue of some attachment extensions not working

- server/handlers/handlers.go
- server/message_hooks.go
- server/message_hooks_test.go
- Added the logic to continue the flow if we get PaymentRequired error from Graph API when updating a message
- Increased the no. of channel members that we are fetching from the Mattermost API
- Modified the unit tests
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/151
> [MI-3132] Fixed the issue of infinite loop when editing messages and a potential bug related to no. of channel members

- server/handlers/handlers.go
- server/handlers/handlers_test.go
- server/message_hooks.go
- server/message_hooks_test.go
- server/msteams/client.go
- server/store/mocks/Store.go
- server/store/store.go
- Created two new store functions for updating last post updateAt time by both MM post id and MS Teams post id
- Modified the return type of error handling function and modified some logs
- Added the logic of updating post last updateAt time when reactions are updated in MM
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/165
> [MI-3161] Fixed the issue of reactions causing infinite loop in both channels and chats

- go.mod
- server/handlers/handlers.go
- server/handlers/handlers_test.go
- server/message_hooks.go
- server/message_hooks_test.go
- server/msteams/client.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
- server/testutils/data.go
Added support to send attachments in DMs and GMs from Teams to MM and MM to Teams.
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/167
> [MI-3165] Add support to send attachments in DMs and GMs

- server/api.go
TODO comment link: https://github.com/Brightscout/mattermost-plugin-msteams-sync/blob/8fbc18bfd33e13678e1657551c49cb388df3bd75/server/api.go#L109
> [MI-3167] Fix TODO comment: Deduplicate calls to refresh subscription when a change request is received from Teams

- server/api.go
- server/command.go
- server/command_test.go
- server/store/mocks/Store.go
- server/store/store.go
- server/store/store_test.go
- Created new store functions for storing and verifying OAuth state
- Added the logic of generating new state and storing it in the KV store with a timeout
- Added the logic of verifying the OAuth state when API call is redirected
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/193
> [MI-3223] Fixed the issue of OAuth state not being used properly

- plugin.json
- server/configuration.go
- server/msteams/client.go
- server/plugin.go
- Added logic to disable and enable syncing of guest users using console config.
- Added logic to deactivate synced users on Mattermost corresponding to MS Teams.
Fixes #218
> [MI-3333] Add console config to handle guest users and deactivated users on MS Teams

- server/handlers/getters.go
- server/plugin.go
Added the logic of setting notify_props of the user when he's being created
> [MI-3395] Fixed the issue of email notifications being sent for synthetic users

- README.md
- docs/azure_setup.md
- plugin.json
- server/handlers/getters.go
- server/handlers/getters_test.go
- server/handlers/handlers_test.go
- Added the logic of using application level permissions for getting the message content inside a linked channel
- Modified the unit tests according to the change
- Modified the documentation for connecting the bot account a little bit
Fixes #217
> [MI-3327] Fixed the issue of replies and messages not being synced from Teams to MM for non-connected user

- server/handlers/attachments.go
- server/handlers/attachments_test.go
- server/handlers/converters.go
- server/handlers/handlers.go
- server/msteams/client.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
- Created a new client function to get hosted content file
- Added the logic to extract image URLs from the message by parsing HTML
- Added the logic to remove the image tags from the message
- Added the logic to download image from MS Teams and upload them on Mattermost with a new name
- Added a new field HostedContentID in the struct ActivityIDs
- Generated new mocks for the Client interface
Fixes https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/247
> [MI-3418] Fixed the issue of embedded images not working from Teams to MM

- plugin.json
Bump plugin version to 1.0.2
Supported Mattermost Server Versions: **7.0.0+**
- 0bfbc895f2a70cba2ddec9137aa1def77937ab8f Added a new config setting for the prompt interval for DMs and GMs (#255 )
- 367aa038d68adc18c2d04fbf227948248fd67ebb Fixed the issue of attachments not opening in DMs/GMs for receivers due to permission issues. (#254 )
> Bump plugin version to 1.0.2

- server/handlers/attachments.go
- server/handlers/attachments_test.go
- server/handlers/converters.go
- server/handlers/handlers.go
- Added the logic to send an ephemeral post from the MS Teams bot if attachment is not delivered due to high size/resolution
- Modified the return type of functions handleAttachments and msgToPost
- Fixed the failing unit tests
Fixes #249
> [MI-3439] Added the logic to send an ephemeral post if an image is not delivered due to size/resolution limits

- server/api_test.go
- server/command.go
- server/command_test.go
- server/handlers/handlers.go
- server/message_hooks.go
- server/message_hooks_test.go
- server/plugin_test.go
- server/store/mocks/Store.go
- server/store/store.go
- Removed the logic of deleting the subscriptions from Teams while receiving change notifications
- Created a new store function for getting channel subscription by Teams channel ID
- Added the logic of deleting the subscription from store and Teams when unlinking a channel
- Changed the log level and added several new logs in message_hooks.go file
Fixes #269
> [MI-3462] Modified the subscription handling when receiving change notifications

- server/message_hooks.go
The message hooks fire every time a message is posted or updated in Mattermost. There is a second debug line in SendChat() that is hit when we send a message to Teams. We should only log posts when they are sent via the second logging instance.
There are other hook logs for things such as reactions. We shouldn't really log these either, but they happen less frequently so we can remove them in a follow-up if we desire.
> Remove debug logs for message hooks

- server/handlers/converters.go
- server/msteams/client.go
- Fixed the issue of channel mentions not working from Teams to MM
- Modified the struct for mention to include conversation ID as well
- Modified the logic for mentioning everyone in a GM
> [MI-3479] Fixed the issue of channel mentions not working from Teams to MM

- server/command.go
- server/command_test.go
- server/handlers/converters.go
- server/handlers/converters_test.go
- server/markdown/markdown.go
- server/msteams/client.go
- server/testutils/data.go
- Reverted the change in connect slash command to add additional error handling
- Removed the logic of converting the message to markdown when replying to a chat in Teams
- Fixed failing unit tests
- Modified the function ConvertToMD in markdown.go
> [MI-3554] Fixed the issue of emojis rendering as HTML and the connect slash command

- README.md
Currently link redirects you to https://github.com/mattermost/mattermost-plugin-msteams-sync/blob/main/github.com/mattermost/mattermost-plugin-msteams-sync/releases
Fixed the structure to redirect to https://github.com/mattermost/mattermost-plugin-msteams-sync/releases instead
> Fix broken link to releases page in README

- plugin.json
Bump plugin version to 1.1.0
Supported Mattermost Server Versions: **7.8.10+**
- 0eb2c41767c0270c2210db166b7e3150cb6d38b5 Added the logic of streaming files from MS Teams and uploading directly to MM without occupying memory (#298)
- 97a837aae4b753ffe59799b44ff6c712204d39dc Adding initial infrastructure for metrics (#306)
- 9c95fa6c49986c84dd45c92f95dd9cdbd9f30589 Added the logic of storing user IDs during the sync user job (#314)
- 1e28476d573da09f04778393bf3aa5b00e27e8d2 Update documentation (#321)
- 97065e34f9b067ce46eb581a51b27ebe2e8ec4b6 Update queue and workers size in handlers (#322)
- 9126c3ce77eb7537e58f549137cedead644da7d7 Fixed the issue of emojis rendering as HTML and the connect slash command (#320)
- 8c7e66bad650201044bdbcf69cdb07bb171bb28e Fixed the issue of emojis showing …
> Bump plugin version to 1.1.0

- server/handlers/getters.go
- server/handlers/handlers_test.go
- server/plugin.go
- server/plugin_test.go
Prefer logging user ids over emails. For now, we follow the existing convention of naming the fields `TeamsUserID` and `MMUserID`.
None.
> prefer logging user ids over emails

- server/metrics/metrics.go
This allows for annotations on the dashboard showing plugin (or server) restart events.
None.
> metric: track the plugin start time

- server/handlers/handlers.go
- server/metrics/metrics.go
Track the capacity of the change event queue (a constant, for now), as well as the length of the queue with a count for each `change_type`.
As I wrote this, I realized we have another, implicit queue of goroutines that are spawned to handle each HTTP request even if the queue is at capacity. This feels like it somewhat defeats the point of the queue, since we'll still accumulate those goroutines until we run out of memory anyway. 
I'm wondering if we should reject the HTTP request if the queue is at capacity. Thoughts? (Alternatively, we should probably at least add a metric for unqueued requests...)
None.
> metric: change event queue length & capacity

- server/plugin.go
Some of my recent logging changes failed to take into account the code paths in which `mmUser` was `nil`. One of those was found and fixed in v1.2.1, this fixes the other.
None.
> Fix mmUser == nil panic

- server/api.go
- server/handlers/handlers.go
- server/plugin.go
Remove the major source of log spam now that we have metrics tracking these calls. We lose the visibility of the raw payload, but -- to date -- this hasn't been useful. There are also potential PII concerns.
None.
> reduce log volume

- plugin.json
Bump plugin version to 1.3.0
None
> Bump plugin version to v1.3.0

- plugin.json
- server/plugin.go
As part of e82ec25fc832b95b16d53d856911ac24ed088e13, I created the metrics service earlier to make it available to the DB Store initialization that occurs in `OnActivate()`. At the time, I took along the code to actually run the metrics server exposed on `:9094`, but for reasons yet unknown, exposing the port during `OnActivate` early in a k8s pod's life cycle makes it unreachable.
Delaying the server start until after `OnActivate` returns -- where it was in v1.2 -- resolves the issue. More investigation is required to understand the root cause, but this should resolve the metric scraping issues.
None.
> delay metrics server start

- server/api.go
- server/command.go
- server/handlers/attachments.go
- server/handlers/attachments_test.go
- server/handlers/converters_test.go
- server/handlers/handlers.go
- server/handlers/handlers_test.go
- server/message_hooks.go
- server/metrics/metrics.go
- server/middleware.go
- server/monitor/subscriptions.go
- server/msteams/client_timerlayer/timerlayer.go
- server/msteams/layer_generators/timer_layer.go.tmpl
- server/plugin.go
- server/plugin_test.go
- server/store/layer_generators/timer_layer.go.tmpl
- server/store/timerlayer/timerlayer.go
With the change to passing around an interface instead of a concrete type, it was necessary to check `metrics != nil`. Improve this by always setting `metrics` to a concrete value, even if the underlying value is `nil`. This allows all calling code to safely use `metrics` without a `nil` check.
None.
> support nil-metrics

- server/api.go
- server/api_test.go
- server/handlers/handlers.go
- server/metrics/metrics.go
- server/metrics/mocks/Metrics.go
Add `discardedReason` to lifecycle event metrics and improving error handling when an invalid webhook secret occurs.
None.
> add discardedReason to lifecycle event metrics

- server/handlers/handlers.go
- server/handlers/recovery_handler.go
- server/handlers/recovery_handler_test.go
Copy the strategy used by the [web hub](https://github.com/mattermost/mattermost/blob/5e94af13022d16dd29c079bc2a68c84a5bac6e9e/server/channels/app/platform/web_hub.go#L370-L375) in the Mattermost server to recover from panics in the activity handler worker.
Extract the logic and add unit tests for normal execution, panics, unexpected exits, and a mixture of all three.
Before, hitting the `/plugins/com.mattermost.msteams-sync/changes` endpoint with a hard-coded panic:
```
{"timestamp":"2023-11-21 17:33:06.917 -04:00","level":"debug","msg":"panic: Here","caller":"plugin/hclog_adapter.go:54","plugin_id":"com.mattermost.msteams-sync"}
{"timestamp":"2023-11-21 17:33:06.917 -04:00","level":"debug","msg":"","caller":"plugin/hclog_adapter.go:54","plugin_id":"com.mattermost.msteams-sync"} …
```
> add recovery handler for activity handler worker

- webapp/src/components/enforceConnectedAccountModal.css
- webapp/src/components/enforceConnectedAccountModal.tsx
- Add padding to enforced connected account modal
- Updated text content of the modal
> [MI-3771] Add padding to enforced connected account modal

- plugin.json
Bump plugin version to v1.4.0. (This won't be necessary at all once we update the tooling and the version is extracted from the nearest tag.)
N/A
> Bump plugin version to v1.4.0

- server/handlers/handlers.go
- server/handlers/worker.go
- server/handlers/worker_test.go
When the plugin stops normally – e.g. as part of rolling the k8s pods – it’s imperative that all outstanding requests be given a chance to terminate normally. Accordingly, let’s make `ActivityHandler.Stop` blocking.
Fixes: https://mattermost.atlassian.net/browse/MM-55491
> MM-55491: ensure handlers stop

- go.mod
- go.sum
- server/plugin.go
Adopt the new [`ServeMetrics`](https://github.com/mattermost/mattermost/pull/24249) hook to expose Prometheus metrics on `:8067/plugins/com.mattermost.msteams-sync/metrics`. This /duplicates/ the existing `:9094/metrics` for now, with the latter to be removed once we finish migrating to the new endpoint in Mattermost Cloud. This is not a breaking change.
As part of this change, we unconditionally initialize the `metricsServer` so it's never `nil`. We also now only stop the metrics server `OnDeactivate`.
Fixes: https://mattermost.atlassian.net/browse/MM-55507
> MM-55507: adopt ServeMetrics hook

- server/plugin.go
- server/plugin_test.go
When I originally drafted the linked ticket, I imagined we would completely eliminate the `p.restart()` method and just keep all the jobs running all the time, with any configuration changes being resolved at run time. This turned out to be trickier than I expected, so I constrained to the primary focus of the overarching epic: avoid anything that disrupts the correct functioning of the application.
With that constrained focus, I'm only preventing the reset of two things: the main app client, and the activity handlers. The jobs being reset are "fine" because they aren't directly user facing. But imagine for a moment that we stop the activity handlers and then go to stop the users sync job, but it's running, so it takes a while: all the time the activity handlers are shut down and the …
> MM-55490: dont reset on configuration changes

- Makefile
- plugin.json
Change our plugin build strategy to target only `linux-amd64` and `linux-arm64`. Previously, we listed all of `linux-*`, `darwin-*` and `windows-*` in our manifest, but then only built `linux-amd64`.
Fixes: https://mattermost.atlassian.net/browse/MM-56175
> only target linux-* architectures

- server/handlers/handlers.go
- server/handlers/handlers_test.go
- server/plugin.go
- server/plugin_test.go
Remove some unused code in anticipation of `start`/`stop` refactoring. In addition to removing the unused `syncSince` implementation (to be replaced with our holistic resiliency efforts), this code rips out the `last_received_change` handling altogether, since we need it per-subscription.
Fixes: https://mattermost.atlassian.net/browse/MM-55494
> remove unused syncSince implementation

- server/plugin.go
In https://github.com/mattermost/mattermost-plugin-msteams-sync/pull/436, I incorrectly removed the `p.metricsServer.Shutdown()` call during `plugin.stop()`, believing it would incorrectly impact the new server managed `ServeMetrics` hook, but this wasn't true: we should indeed stop listening on the requested port if the configuration so changes, and we can continue handling `ServeMetrics` without issue.
Relates-to: https://mattermost.atlassian.net/browse/MM-55507
> restore metrics server stop

- server/api.go
- server/command.go
- server/plugin.go
We had a mutex guarding msteamsAppClient, but it wasn't being used consistently. Fix that, and change it to a `RWMutex` to minimize the critical sections. Note that we never hold the mutex while using client: we're effectively just protecting the pointer.
Finally, I note we currently don't ever change the `msteamsAppClient`, even if the configuration changes. So this mutex is also technically unneeded. But it probably makes sense to support reconnecting the client on a real configuration change in the future without having to restart the server.
Relates-to: https://mattermost.atlassian.net/browse/MM-55490
> guard msteamsAppClient

- Makefile
- plugin.json
This is mostly a temporary change until https://github.com/mattermost/matterbuild/pull/97 is merged and we can be more selective about the versions we intend to ship and support.
I'm hoping to get cut v1.5.0 as quickly as possible and we'll "fix" this in v1.6.0.
Relates-to: https://mattermost.atlassian.net/browse/MM-55528
> Build windows and darwin to solve build issues

- Makefile
After the update of the starter template, the `make generate` command disappeared, and it was convenient to generate layers and mocks. This PR restores it.
> Restoring the generate make command

- server/metrics/dashboards/cloud.json
- server/plugin.go
Revert https://github.com/mattermost/mattermost-plugin-msteams-sync/pull/439, as it's incorrect to `.Shutdown()` and try to `.ServeAndListen()` on the same `http.Server`. Whenever the server configuration changes, we `reset()` and effectively kill the metrics server. In the past, we completely reset the `http.Server` on `reset()`, so it wasn't an issue, but with the new `ServeMetrics` hook, we (currently) keep around `handler` for reuse there.
Since all of this is going away once we can switch over exclusively to `ServeMetrics` in v1.6.0, ignore the fact that the revert means we no longer respond to configuration changes re: metrics. It's not an issue where we currently intend to deploy the plugin, and won't be an issue for long.
While I'm in here, update the `cloud.json` dashboard …
> MM-56364: fix metrics stop on configuration change

- Makefile
- build/manifest/main.go
- plugin.json
Copy the changes from https://github.com/mattermost/mattermost-plugin-calls/pull/597 to slim down to just building `plugin-linux-amd64` and `plugin-linux-arm64` while still allowing developers to build for an arbitrary local platform when `MM_SERVICESETTINGS_ENABLEDEVELOPER` is true.
This will slim down the releases and make it easier to upload to test servers without bumping the max upload size.
None.
> build only linux* but support devs

- build/manifest/main.go
Fix this auto generation:
```diff
-    "release_notes_url": "https://github.com/mattermost/mattermost-plugin-msteams-syncreleases/tag/v1.5.3",
+    "release_notes_url": "https://github.com/mattermost/mattermost-plugin-msteams-sync/releases/tag/v1.5.3",
```
None.
> fix release notes url generation

- server/api_test.go
- server/plugin.go
- server/plugin_test.go
Don't initialize the API on every single HTTP request. Besides the performance overhead, this is spamming the plugin API to `GetBundlePath` after upgrading to v1.5.3.:
Fixes: https://mattermost.atlassian.net/browse/MM-55489
> initialize API only once

- build/manifest/main.go
Fix the case when `DEFAULT_*` is not defined, e.g. the regular build.
None.
> fix defaultGoOs/defaultGoArch when not exported

- server/ce2e/iframe_test.go
Enhances error message when ce2e test fails for fetching iframe files.
There was a set of [PRs failing](https://github.com/mattermost/mattermost-plugin-msteams-sync/actions/runs/7586270513/job/20664036753?pr=461) but the error was simply HTTP 404.  This PR adds the url used to ensure the domain, port, etc are correct.
NONE
> Better error msg on test fail

- server/msteams/client.go
- server/msteams/client_disconnectionlayer/disconnectionlayer.go
- server/msteams/layer_generators/disconnection_layer.go.tmpl
This fixes the problem of having not valid sessions for msteams and still not reciving the message for reconnect.
Now the user gets properly notified and the session is removed from the database.
> Fixing issue on reconnect required notification

- plugin.json
- server/command.go
- server/command_test.go
- server/configuration.go
- server/handlers/attachments.go
- server/handlers/attachments_test.go
- server/handlers/getters_test.go
- server/handlers/handlers.go
- server/handlers/handlers_test.go
- server/handlers/mocks/PluginIface.go
- server/message_hooks.go
- server/message_hooks_test.go
- server/metrics/metrics.go
- server/plugin.go
- server/testutils/containere2e/containere2e.go
Adds new configuration options to disable syncing reactions, file attachments, and linked channels, all defaulting to false. Note that this does not unlink existing channels.
When the configuration for linked channels is toggled, the slash command is updated appropriately.
Fixes: https://mattermost.atlassian.net/browse/MM-56676
Fixes: https://mattermost.atlassian.net/browse/MM-56677
Fixes: https://mattermost.atlassian.net/browse/MM-56810
> Disable reactions / files attachments / linked channels by default

- server/api.go
As per https://pkg.go.dev/crypto/rsa@go1.20.12#DecryptOAEP:
> The random parameter is legacy and ignored, and it can be as nil.
Let's make this explicitly `nil` as such.
Fixes: https://mattermost.atlassian.net/browse/MM-56081
> set deprecated parameter to nil

- server/monitor/monitor.go
- server/monitor/subscriptions.go
- server/monitor/subscriptions_test.go
- server/plugin.go
Honour the existing "Sync direct and group messages" setting, skipping the attempt to register a global chats subscription accordingly.
None.
> stop managing global chats subscription if disabled

- .golangci.yml
- server/api.go
- server/automute.go
- server/automute_channel.go
- server/automute_channel_test.go
- server/automute_preferences.go
- server/automute_test.go
- server/automute_user_connect.go
- server/automute_user_connect_test.go
- server/command.go
- server/command_test.go
Continuing from https://github.com/mattermost/mattermost-plugin-msteams-sync/pull/477, since automuting is enabled when a user is both connected and has their primary platform set to MS Teams, we need to also potentially enable or disable automuting when a user connects or disconnects from MS Teams.
https://mattermost.atlassian.net/browse/MM-56501
> MM-56501 Enable/disable automuting when a user connects/disconnects

- assets/info-page/index.html
`widow.close` generally won't work, but even if it doesn't, fall back to showing the "You can now close this window" prompt. I've also added `target="_blank"` for the learn more links to avoid losing this page state.
My edit threw in some random whitespace fixes as well which seemed harmless.
None.
> fix Continue button during oAuth flow

- assets/info-page/index.html
I regressed the behaviour, which closed the window before the promise was resolved. In my case, since the window never actually closed, the fetch had a chance to succeed. On browsers that honoured `window.close`, the `fetch` was interrupted and the settings never saved.
None yet.
> fix closeInfoPage to call on promise resolution

- README.md
There's no good reason the LICENSE is the most prominent paragraph in the README. Let's move it to the bottom, like we do for https://github.com/mattermost/mattermost-plugin-ai.
None.
> Move LICENSE to bottom of README

- server/automute_channel_test.go
- server/automute_test.go
I made `AutomuteAPIMock` match the server behaviour in MM-56776, so once https://github.com/mattermost/mattermost/pull/26226 goes in, the mock can also be "fixed". At the moment, we're planning for that fix to ship in 9.6, so fixing the corresponding bug on the MS Teams plugin (newly created GMs won't have automuting applied) will simply require upgrading to MM 9.6 once that's out
https://mattermost.atlassian.net/browse/MM-56776
> MM-56776 Update mock to fix ChannelHasBeenCreated not being called for GMs

- server/selective_sync.go
- server/selective_sync_test.go
Currently, with Selective Sync turned on, self chats will never sync. This is actually a valuable test tool and may people may "test" the system using there self channels. 
This PR checks the number of members in the channel and allows it to sync if there is only 1.
> Allow self chats to sync when selective sync is true

- server/e2e/formatting_test.go
- server/markdown/markdown.go
Implements a round robin test of formatting. SendsChat to MS Teams and checks "sync'ed" message from Mattermost to ensure expected message is sync'ed. 
Fixes https://mattermost.atlassian.net/browse/MM-57201
> add E2E formatting tests

- server/ce2e/plugin_test.go
- server/handlers/attachments.go
- server/handlers/attachments_test.go
- server/handlers/converters.go
- server/handlers/converters_test.go
- server/handlers/handlers.go
- server/message_hooks.go
- server/message_hooks_test.go
Don't surprise end users if file attachments are disabled by simply ignoring them: send a message (inside Mattermost) if a file attachment from Teams is skipped or if a user tries to send an attachment from Mattermost.
**sent from Teams**
**sent from Mattermost**
This is not sent as an ephemeral message, partly since it applies to all channel participants, but also because an ephemeral message will disappear on reload.
Fixes: https://mattermost.atlassian.net/browse/MM-56811
> MM-56811: notify when attachments not synced

- server/metrics/dashboards/cloud.json
Update the snapshot of the Cloud dashboard we use for monitoring this plugin. Note that this remains architected towards our Mattermost Cloud environment, with a `$namespace` filter and various datasource variables. Nevertheless, it's a good starting point for building a single-installation version, and a future iteration may find a way to make the `$namespace` parameter optional
None.
> update Grafana dashboard for Cloud, stripping out hard-coded links

- server/command.go
- server/command_test.go
When running the `promote` command, the first argument is accepted with or without a `@`, while the second does not support a `@` at all. This PR allows both arguments to be prefixed by a `@`, that will immediately be trimmed.
https://mattermost.atlassian.net/browse/MM-56908
> [MM-56908] Make promote command accepts @ for both arguments

- server/api.go
Use `ConstantTimeCompare` instead of `!=` to reduce the risk of timing attacks on the webhook secret
https://mattermost.atlassian.net/browse/MM-57072
> [MM-57072] Use ConstantTimeCompare to prevent timing attack

- server/api.go
- webapp/src/index.tsx
- Log when connection invite successfully sent. 
- Also adds `clean up activity handler` during `uninitialize` that was missing in #544.
- https://mattermost.atlassian.net/browse/MM-57367
> MM-57367: log when invite sent

- server/command.go
- server/message_hooks.go
In working through some changes to address invalid "error" logs, I took the opportunity to rely on `channel.IsGroupOrDirect()` to replace the manual comparisons. There should be no semantic changes from this PR.
Relates-to: https://mattermost.atlassian.net/browse/MM-56719
> use IsGroupOrDirect for clarity

- server/api.go
- server/api_test.go
- webapp/src/client.ts
- webapp/src/index.tsx
- webapp/src/types/mattermost-webapp/index.d.ts
Show the number of connected users on the system console for administrators.
Fixes: https://mattermost.atlassian.net/browse/MM-57350
> MM-57120: show connected users stat

- server/message_hooks.go
- server/message_hooks_test.go
Just found a case I didn't see before for setting EmailVerified to `true` when doing an autopromotion!
Previous PR: https://github.com/mattermost/mattermost-plugin-msteams/pull/548
https://mattermost.atlassian.net/browse/MM-57209
> [RE:MM-57209]  Set EmailVerified to true when autopromoting through hook

- server/plugin.go
- server/plugin_test.go
Partially fixes https://mattermost.atlassian.net/browse/MM-56887
> [MM-56867] Fix metrics by not counting disabled users

- server/handlers/handlers.go
- server/handlers/handlers_test.go
- server/message_hooks.go
- server/message_hooks_test.go
- server/metrics/metrics.go
- server/metrics/mocks/Metrics.go
Monitor the delta between when a message is created on one platform and when it's recorded as such on the other. We acknowledge that without synchronized clocks between Mattermost and Teams, the absolute value here isn't necessarily accurate. But the idea is to measure the variability in the delay between messages flowing in each direction.
As part of this change, drop the unused "confirmed message" metric.
Fixes: https://mattermost.atlassian.net/browse/MM-57534
> MM-57534: monitor message creation delay

- server/command.go
- server/command_test.go
Add a `/msteams status` slash command to show connection status:
and similarly:
Fixes: https://mattermost.atlassian.net/browse/MM-57508
> MM-57508: status slash command

- go.mod
- server/handlers/getters.go
- server/handlers/getters_test.go
- server/handlers/handlers.go
- server/handlers/mocks/PluginIface.go
- server/plugin.go
When creating a synthetic user from a DM/GM, we set a remoteID based on the user UUID instead of using the plugin remoteID.
Example of how it's done for the syncUsers job: https://github.com/mattermost/mattermost-plugin-msteams/blob/main/server/plugin.go#L727
https://mattermost.atlassian.net/browse/MM-57568
> [MM-57568] Synthetic user created from DM/GM have wrong RemoteID

- assets/info-page/index.html
Firefox ESR doesn't support nested CSS selectors: switch back to the old-style version instead, and fix a handful of other syntax errors. Push it through a CSS beautifier as well.
Fixes: https://mattermost.atlassian.net/browse/MM-57506
> MM-57506: use old CSS syntax

- server/store/sqlstore/helper_test.go
- server/store/sqlstore/migrations.go
- server/store/sqlstore/migrations_test.go
- server/store/sqlstore/store.go
- Add UNIQUE index on our users table to ensure msteamsuserid is unique.
- Created a migration to ensure we only have one msteamsuserid before apply the index
- Move migrations related methods to the migration file.
This PR does not include any check on the constraint on purpose: this will help us find where and why this happens in the first place.
https://mattermost.atlassian.net/browse/MM-56982
> [MM-56982] UNIQUE index on msteamsuserid 

- server/command.go
- server/handlers/getters.go
- server/handlers/getters_test.go
- server/message_hooks.go
- server/message_hooks_test.go
- server/plugin.go
- server/plugin_test.go
- server/store/sqlstore/migrations.go
- server/store/sqlstore/store.go
`UpdateUser` ignores the `EmailVerified`, so our `UpdateUser` calls have no effect and we would try to do it at every `syncUser`. In addition, doing the Uodate one by one was quite hurtful.
This fixes the issue by migrating all necessary users in one query during a migration.
N/A
> Set EmailVerified to true for all remote users during migration

- server/message_hooks.go
Set the rootID for the new post to the existing posts root id. Result is if null, new post displays in center section and if a reply it will appear in the thread list.
Fixes https://mattermost.atlassian.net/browse/MM-57565
> MM-57565 - Set root id if it exists on attachment sync warning

- server/api.go
When updating an ephemeral post, the date and user were not being set. Set the user to bot and the date to now.
fixes https://mattermost.atlassian.net/browse/MM-57902
> MM-57902 Date doesn't get set on updated ephemeral post 

- server/api.go
- server/command.go
- server/command_test.go
When a user disconnects from MS Teams, set the primary platform to 'matttermost'. Otherwise when messaged from another connected MM primary user, messages continue to sync.
Fixes https://mattermost.atlassian.net/browse/MM-57906
> MM-57906 Update platform preference when disconnecting

- server/api.go
- server/connect.go
Invite messages need to be send from bot, but not as ephemeral messages.
> Send invite message as bot message, not ephemeral

- server/api.go
- server/connect.go
* send invite message as bot message, not ephemeral
* update connect message
* check error
* cleanup
* edit post message to not set id
(cherry picked from commit 9c70367b8e1b8bc62b0ae3dedd92a92cda2262bb)
> Send invite message as bot message, not ephemeral (#607)

- server/api.go
- server/store/sqlstore/store.go
Fix bug where whitelist uploads would fail if size >100.
> Fix whitelist upload batching

- server/connect.go
Updates invite message. 
Fixes https://mattermost.atlassian.net/browse/MM-57955
> MM-57955 - update invite message

- server/api.go
- server/store/sqlstore/store.go
Cherry pick #612. Fix bug where whitelist uploads would fail if size >100.
> CP 612 Fix whitelist upload batching

- server/bot_messages.go
- server/handlers/handlers.go
- Hide messages that ask a user to "Click here to connect".
- The message will still display if a connected user loses their connection `OnDisconnectedTokenHandler` and if the command `/msteams connect` is run. 
- The warning message regarding messages not being delivered will not be displayed.
Code was only commented out, as we expect to re-enable in the future.
Fixes https://mattermost.atlassian.net/browse/MM-57920
> Hide connect message, hide attachment message on update

- server/plugin.go
We are calling GetUser for each synthetic during the syncUsers job, but we only need to make this call if autopromote is `on`.
Reminder: the reason why we need this call is because `GetUsers` does not return `AuthData`: it's sanitized, so we make `GetUser` to get this info. Ideally, plugins should have access to more unsanitized data, but it involves a much heavier change on mattermost server, getting security validation etc... the change is probably not worth investing time in right now.
I don't expect this PR to have a significant positive perf impact as Jesus believes that `GetUser` is pulling data from cache rather than DB, but it's probably still better to only do the call when needed rather than all the time.
I think for QA, just making sure that the syncUsers job will works as …
> [MM-57821] Reduce number of calls to GetUser in syncUsers

- server/automute_channel_test.go
- server/automute_preferences_test.go
- server/automute_test.go
- server/helper_test.go
This extracts the portion of https://github.com/mattermost/mattermost-plugin-msteams/pull/586 that finished rewriting the automute tests using the new (mock free) testing framework.
None.
> rewrite automute tests

- server/api_test.go
- server/message_hooks_test.go
- server/metrics/metrics.go
- server/metrics/mocks/Metrics.go
- server/msteams/client_timerlayer/timerlayer.go
- server/msteams/layer_generators/main.go
- server/msteams/layer_generators/timer_layer.go.tmpl
Status code will be set at 2XX for all successful requests as we don't have a returning code coming from the SDK in those cases. For errors, the status code will come from the SDK error and will be set to zero if not present.
https://mattermost.atlassian.net/browse/MM-56678
> Track status_code as part of the MSGraphClient method duration

- server/automute_preferences_test.go
- server/bot_messages.go
- server/command.go
- server/command_test.go
- server/connect.go
- server/message_hooks.go
- server/plugin.go
- server/plugin_test.go
Naming is king. Finally changing the `userID` property to `botUsertID`!
Not the most important PR... or is it?
> (chore) Rename plugin's userID to botUsertID

- server/bot_messages.go
- server/command.go
Creates a new function to send a "connect" message as either ephemeral or non-ephemeral
Fixes https://mattermost.atlassian.net/browse/MM-58134
> MM-58134- Disconnect should not be ephemeral message

- server/automute.go
- server/command.go
- server/command_test.go
- server/plugin.go
- server/preferences.go
- server/preferences_test.go
- server/store/storemodels/storemodels.go
This PR introduces the preference for the new notification feature. the UI will come in a future PR (probably right after this is merged), we started with the slash command to get something quickly.
- adds a slash command to allow the user to configure it.
- add methods to set/get the preference for the user
https://mattermost.atlassian.net/browse/MM-58322
> [MM-58322] Add notification preference slash command

- server/metrics/metrics.go
- server/metrics/mocks/Metrics.go
- server/notifications.go
Keep track of the number of notifications emitted to users, including whether or not they are for group chats (>= members) and have any attachments.
Fixes: https://mattermost.atlassian.net/browse/MM-58299
> MM-58287: track notification metrics

- server/api.go
- server/api_test.go
- server/bot_messages.go
- server/bot_messages_test.go
- server/preferences.go
When dismissing a welcome message from the MS Teams bot re: notifications, show a message explaining how to change those settings instead of just deleting it outright:
Fixes: https://mattermost.atlassian.net/browse/MM-58580
> MM-58580: show message on welcome bot dismiss

- server/api.go
- webapp/src/client.ts
Check the response header from the server before trying to interpret the response as JSON. Not all endpoints reply with JSON. And now those that should now do so explicitly.
Fixes: https://mattermost.atlassian.net/browse/MM-58702
> MM-58702: don't assume JSON endpoint

- plugin.json
For new plugin installs, default the notifications experience on at the admin level (individual users still need to enable for themselves).
Fixes: https://mattermost.atlassian.net/browse/MM-59509
> default notifications on

- server/attachments.go
- server/attachments_test.go
Explicitly check for a `contentType` of `reference` before trying to process the attachment as a file attachment.
Fixes: https://mattermost.atlassian.net/browse/MM-59273
> explicitly check contentType of reference before downloading files

- server/bot_messages.go
- server/credentials.go
- server/handlers.go
- server/handlers_test.go
- server/metrics/dashboards/dashboard.json
- server/metrics/metrics.go
- server/metrics/mocks/Metrics.go
- server/msteams/client.go
- server/msteams/client_disconnectionlayer/disconnectionlayer.go
- server/msteams/client_timerlayer/timerlayer.go
- server/msteams/clientmodels/clientmodels.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
- server/notifications.go
- server/presence.go
- server/store/mocks/Store.go
- server/store/sqlstore/public_methods.go
- server/store/timerlayer/timerlayer.go
- server/subscriptions.go
If a user gets a Teams notification in Mattermost and then hops over to Teams, they continue to get “spammed” by messages in the ensuing chat. Let’s detect user presence and only notify users if they aren’t available in Teams.
This also means that while a user is "Available" in Teams, they won't get notifications in Mattermost. By default, this will be the state for 5 minutes after a user was last active. Note that if a user has their mobile device connected, but in the background, it won't count against the user being seen by Mattermost as "Available" in Teams.
Fixes: https://mattermost.atlassian.net/browse/MM-60005
> MM-60005: dont notify if present

- Makefile
- server/store/sqlstore/store.go
After a Go upgrade, I ran into issues with `golangci-lint`, which in tun required upgrading that tooling.
None.
> upgrade and placate golangci-lint

- server/presence.go
If a user chooses to "Appear Offline", treat this like do we do when the user is manually away and start delivering messages to Mattermost.
Fixes: https://mattermost.atlassian.net/browse/MM-60717
> MM-60717: add OffWork to presence detection

- Makefile
Fix an issue building on MacOS, copying this change from other plugins that have already updated.
None
> fix --disable-copyfile

- server/api_test.go
- server/iframe.go
To embed Mattermost and allow sign-on with a configured provider, we need to extend the `frame-src` directive accordingly. Similarly, add the `self` directive while we're in here.
None
> allow iframe redirect to configured SamlIdpURL

- server/api_test.go
- server/iframe.go
Remove the `default-src 'none'` directive and `frame-src` directives, as IDPs may redirect arbitrarily depending on their backend implementation.
None
> allow all frame-src for now

- server/iframe.go
In Chrome browsers the iFrame hosting MM web client was showing scroll bars due to lack of border setting.  This PR fixes the issue by explicitly setting a border (none) and setting a left position.
NONE
> Fix scroll bars appearing on iFrame

- server/iframe.go
Fixes the load error `There was a problem reaching this app` by initializing the MS Teams SDK in the iFrame document, and calling `notifySuccess()`
https://mattermost.atlassian.net/browse/MM-63346
> MM-63346 Fix load error `There was a problem reaching this app`

- server/iframe.go
This PR fixes the issue of running our tab app inside O365 hub (https://m365.cloud.microsoft).  This requires a newer SDK version, and adjustments to the init calls.  I also added our site URL to the list of cross-domain origins so that the SDK can communicate with our frame. 
https://mattermost.atlassian.net/browse/MM-63372
> Upgrade to latest SDK; adjust init calls for new version

- Makefile
Fixes crash in mockery.
```
❯ make generate
/usr/local/go/bin/go install github.com/vektra/mockery/v2/...@v2.18.0
go: downloading github.com/vektra/mockery/v2 v2.18.0
go: downloading golang.org/x/crypto v0.0.0-20220525230936-793ad666bf5e
go: downloading golang.org/x/tools v0.5.0
go: downloading github.com/chigopher/pathlib v0.12.0
go: downloading github.com/spf13/viper v1.12.0
go: downloading github.com/rs/zerolog v1.27.0
go: downloading github.com/spf13/cobra v1.4.0
go: downloading github.com/stretchr/testify v1.7.2
go: downloading github.com/subosito/gotenv v1.4.0
go: downloading github.com/spf13/cast v1.5.0
go: downloading github.com/spf13/afero v1.8.2
go: downloading github.com/fsnotify/fsnotify v1.5.4
go: downloading github.com/magiconair/properties v1.8.6
go: downloading …
```
> Bump mockery version

- server/iframe.html
- server/msteams/client.go
This PR relies on `navigateToApp` to redirect the user to the deeplink manually when we receive a `subEntityId` that comes from an userActivity.
This fires of if the parameter is set, so when an user activity is opened in the "Activities" tab application, teams will "redirect" the user to the Mattermost tab application, and then the tab will load as usual.
Out tab app will also load this code and fire the `navigateToApp` call, but from my testing it seems that the Teams SDK is smart enough to avoid navigating to the page the user is already in, becoming a no-op in our tab application loading the iframe URL as usual.
> feat: make the iframe navigate to the app manually

- plugin.json
- server/configuration.go
- server/iframe.go
- server/iframe.html
- server/mentions.go
- server/msteams/client.go
- server/msteams/interface.go
- server/msteams/mocks/Client.go
mproves and refactors logic that extracts `@mentions` from the post and checks if an user should be mentioned from the received message.
Currently handling:
- DMs
- GMs
- `@user`
- `@group`
- `@channel` / `@all`
- `@here`
Missing:
- User custom keywords
- Check for user notification preferences
Requires: https://github.com/mattermost/mattermost-plugin-msteams/pull/804
> feat: improve mention retrieval from posts, allows to disable notifications

- Makefile
Fixes running `make check-style` locally:
```
Error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23.1)
Failed executing command with error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23.1)
```
NONE
> Update golangci-lint version to match MM server

- server/iframe.html
Check if the Tenant ID in the configuration is already hardcoded in the `tenantMap` before adding it.
> fix: check tenant id before adding the one being set up

- server/api.go
- server/iframe.go
- server/iframe.html
- server/jwt.go
- server/jwt_test.go
- server/mentions.go
- server/plugin.go
- server/store/pluginstore/store.go
- [fix: redirect iframe to site url if there's an error](https://github.com/mattermost/mattermost-plugin-msteams/commit/4d4b49da5cc02a8871500c14d7132cc2f12770af): We weren't catching errors on the `getContext` call, leaving the frame in `about:blank`.
- [fix: retrieve the correct property from the user](https://github.com/mattermost/mattermost-plugin-msteams/commit/a83e5e5fe37711df3fe31b25ddada58b9e90ccea): We were storing the object id as `oid` but trying to use it as `user_id`, breaking the login flow.
- @wiggin77 you were hitting this, that's why SSO wasn't working on your app
- [feat: store user metadata in the plugin kvstore](https://github.com/mattermost/mattermost-plugin-msteams/pull/815/commits/46d3b7569c6e82a5f3816d508f66a43690d3db7f)
> fix: sso audience and other minor fixes

- server/iframe.go
- server/jwt.go
- server/jwt_test.go
Use the `noroute` param in the backend to determine if we need to validate the audience against community or to the set up parameters in the plugin configuration.
> feat: check set up audience if noroute is set

- plugin.json
- server/configuration.go
- server/monitor.go
- server/plugin.go
Provides a way to disable the sync job thus avoiding error logs and unneeded Graph API calls.
To disable, set the `Enable sync job` to false via plugin config in the system console. 
NONE
> Disable sync job via plugin config

- server/msteams/client.go
- Fixed nil pointer dereference in GetFileSizeAndDownloadURL when processing file attachments
- Added proper error handling for nil additionalData
- Added safer type assertion for downloadURL that handles both string and *string types 
https://mattermost.atlassian.net/browse/MM-63675
N/A
> MM-63675: Fix nil pointer dereference in GetFileSizeAndDownloadURL

- server/iframe.go
- server/jwt.go
- server/jwt_test.go
Require the `ServiceSettings.EnableDeveloper` and `ServiceSettings.EnableTesting` flags to allow local development mode that doesn't enforce JWT validation.
None
> combine EnableDeveloper and EnableTesting

- server/iframe.html
- server/mentions.go
- Pass down the noroute parameter if present to the authenticate iframe src
- Check if we have user IDs to send user activities to before sending the API call to avoid the `Recipients is empty` error
> fix: passthrough noroute parameter to authenticate and avoid sending user activities without users

- Makefile
Recover https://github.com/mattermost/mattermost-plugin-msteams/pull/814 after the reset.
None
> skip assets.go when building (#814)

- go.mod
- go.sum
Updated MM server public and model dependencies to get latest changes in the plugin API that have support for the new Enterprise Advanced SKU. 
https://mattermost.atlassian.net/browse/MM-63646
> Add support for Enterprise Advanced SKU
